platform :ios, '8.0'

source 'git@github.com:CocoaPods/Specs.git' 

def common
    pod 'WeexSDK', '0.11'
    pod 'SDWebImage', '4.0.0'
end


target 'habit-release' do
    common
end

target 'habit-test' do
    common
end