platform :ios, '8.0'

source 'git@github.com:CocoaPods/Specs.git' 

def common
    pod 'WeexSDK', '0.15.1'
    pod 'SDWebImage', '4.0.0'
    pod 'TBXML', '~> 1.5'
    pod 'SSZipArchive', '~> 1.8.1'
end


target 'habit-release' do
    common
end

target 'habit-test' do
    common
end